# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: onvif_firmware_update.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='onvif_firmware_update.proto',
  package='onvif_firmware_update',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1bonvif_firmware_update.proto\x12\x15onvif_firmware_update\"\\\n\x15UpdateFirmwareRequest\x12\x0f\n\x07version\x18\x01 \x01(\t\x12\x1d\n\x10reboot_time_secs\x18\x02 \x01(\x05H\x00\x88\x01\x01\x42\x13\n\x11_reboot_time_secs\"&\n\x13UpdateFirmwareReply\x12\x0f\n\x07version\x18\x01 \x01(\t2~\n\x0e\x46irmwareUpdate\x12l\n\x0eUpdateFirmware\x12,.onvif_firmware_update.UpdateFirmwareRequest\x1a*.onvif_firmware_update.UpdateFirmwareReply\"\x00\x62\x06proto3'
)




_UPDATEFIRMWAREREQUEST = _descriptor.Descriptor(
  name='UpdateFirmwareRequest',
  full_name='onvif_firmware_update.UpdateFirmwareRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='onvif_firmware_update.UpdateFirmwareRequest.version', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='reboot_time_secs', full_name='onvif_firmware_update.UpdateFirmwareRequest.reboot_time_secs', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_reboot_time_secs', full_name='onvif_firmware_update.UpdateFirmwareRequest._reboot_time_secs',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=54,
  serialized_end=146,
)


_UPDATEFIRMWAREREPLY = _descriptor.Descriptor(
  name='UpdateFirmwareReply',
  full_name='onvif_firmware_update.UpdateFirmwareReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='onvif_firmware_update.UpdateFirmwareReply.version', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=148,
  serialized_end=186,
)

_UPDATEFIRMWAREREQUEST.oneofs_by_name['_reboot_time_secs'].fields.append(
  _UPDATEFIRMWAREREQUEST.fields_by_name['reboot_time_secs'])
_UPDATEFIRMWAREREQUEST.fields_by_name['reboot_time_secs'].containing_oneof = _UPDATEFIRMWAREREQUEST.oneofs_by_name['_reboot_time_secs']
DESCRIPTOR.message_types_by_name['UpdateFirmwareRequest'] = _UPDATEFIRMWAREREQUEST
DESCRIPTOR.message_types_by_name['UpdateFirmwareReply'] = _UPDATEFIRMWAREREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

UpdateFirmwareRequest = _reflection.GeneratedProtocolMessageType('UpdateFirmwareRequest', (_message.Message,), {
  'DESCRIPTOR' : _UPDATEFIRMWAREREQUEST,
  '__module__' : 'onvif_firmware_update_pb2'
  # @@protoc_insertion_point(class_scope:onvif_firmware_update.UpdateFirmwareRequest)
  })
_sym_db.RegisterMessage(UpdateFirmwareRequest)

UpdateFirmwareReply = _reflection.GeneratedProtocolMessageType('UpdateFirmwareReply', (_message.Message,), {
  'DESCRIPTOR' : _UPDATEFIRMWAREREPLY,
  '__module__' : 'onvif_firmware_update_pb2'
  # @@protoc_insertion_point(class_scope:onvif_firmware_update.UpdateFirmwareReply)
  })
_sym_db.RegisterMessage(UpdateFirmwareReply)



_FIRMWAREUPDATE = _descriptor.ServiceDescriptor(
  name='FirmwareUpdate',
  full_name='onvif_firmware_update.FirmwareUpdate',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=188,
  serialized_end=314,
  methods=[
  _descriptor.MethodDescriptor(
    name='UpdateFirmware',
    full_name='onvif_firmware_update.FirmwareUpdate.UpdateFirmware',
    index=0,
    containing_service=None,
    input_type=_UPDATEFIRMWAREREQUEST,
    output_type=_UPDATEFIRMWAREREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_FIRMWAREUPDATE)

DESCRIPTOR.services_by_name['FirmwareUpdate'] = _FIRMWAREUPDATE

# @@protoc_insertion_point(module_scope)
