# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import onvif_firmware_update_pb2 as onvif__firmware__update__pb2


class FirmwareUpdateStub(object):
    """The greeter service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UpdateFirmware = channel.unary_unary(
                '/onvif_firmware_update.FirmwareUpdate/UpdateFirmware',
                request_serializer=onvif__firmware__update__pb2.UpdateFirmwareRequest.SerializeToString,
                response_deserializer=onvif__firmware__update__pb2.UpdateFirmwareReply.FromString,
                )


class FirmwareUpdateServicer(object):
    """The greeter service definition.
    """

    def UpdateFirmware(self, request, context):
        """Sends a greeting
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FirmwareUpdateServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UpdateFirmware': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateFirmware,
                    request_deserializer=onvif__firmware__update__pb2.UpdateFirmwareRequest.FromString,
                    response_serializer=onvif__firmware__update__pb2.UpdateFirmwareReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'onvif_firmware_update.FirmwareUpdate', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class FirmwareUpdate(object):
    """The greeter service definition.
    """

    @staticmethod
    def UpdateFirmware(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/onvif_firmware_update.FirmwareUpdate/UpdateFirmware',
            onvif__firmware__update__pb2.UpdateFirmwareRequest.SerializeToString,
            onvif__firmware__update__pb2.UpdateFirmwareReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
